export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    GET_CART: 'GET_CART',
    SAVE_CART_START: 'SAVE_CART_START',
    SAVE_CART_SUCCESS: 'SAVE_CART_SUCCESS',
    SAVE_CART_FAILURE: 'SAVE_CART_FAILURE',
    SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE' 
};